from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='0001_initial'; down_revision=None; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('users',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('telegram_id',sa.BigInteger(),nullable=False),sa.Column('username',sa.String(64)),sa.Column('full_name',sa.String(255),nullable=False),sa.Column('language',sa.String(5),nullable=False,server_default=''),sa.Column('plan_code',sa.String(20),nullable=False),sa.Column('plan_expires_at',sa.DateTime(timezone=True)),sa.Column('is_banned',sa.Boolean(),nullable=False),sa.Column('referrals_count',sa.Integer(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('last_active_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_users_telegram_id','users',['telegram_id'],unique=True); op.create_index('ix_users_username','users',['username']); op.create_index('ix_users_plan_code','users',['plan_code']); op.create_index('ix_users_is_banned','users',['is_banned'])
    op.create_table('plans',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('code',sa.String(20),nullable=False),sa.Column('name_uz',sa.String(80),nullable=False),sa.Column('name_en',sa.String(80),nullable=False),sa.Column('name_ru',sa.String(80),nullable=False),sa.Column('daily_ai_limit',sa.Integer(),nullable=False),sa.Column('daily_ticket_limit',sa.Integer(),nullable=False),sa.Column('image_enabled',sa.Boolean(),nullable=False),sa.Column('voice_enabled',sa.Boolean(),nullable=False),sa.Column('file_enabled',sa.Boolean(),nullable=False),sa.Column('price_monthly',sa.Integer(),nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False)); op.create_index('ix_plans_code','plans',['code'],unique=True)
    op.create_table('channels',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('chat_id',sa.BigInteger(),nullable=False),sa.Column('title',sa.String(255),nullable=False),sa.Column('invite_url',sa.String(500),nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False)); op.create_index('ix_channels_chat_id','channels',['chat_id'],unique=True)
    op.create_table('operators',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('telegram_id',sa.BigInteger(),nullable=False),sa.Column('role',sa.String(30),nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False)); op.create_index('ix_operators_telegram_id','operators',['telegram_id'],unique=True)
    op.create_table('tickets',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('public_id',sa.String(16),nullable=False),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id'),nullable=False),sa.Column('operator_id',sa.Integer(),sa.ForeignKey('operators.id')),sa.Column('subject',sa.String(255),nullable=False),sa.Column('status',sa.String(20),nullable=False),sa.Column('priority',sa.String(20),nullable=False),sa.Column('ai_summary',sa.Text()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_tickets_public_id','tickets',['public_id'],unique=True); op.create_index('ix_tickets_user_id','tickets',['user_id']); op.create_index('ix_tickets_status','tickets',['status'])
    op.create_table('ticket_messages',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('ticket_id',sa.Integer(),sa.ForeignKey('tickets.id',ondelete='CASCADE'),nullable=False),sa.Column('sender_type',sa.String(20),nullable=False),sa.Column('sender_telegram_id',sa.BigInteger()),sa.Column('content',sa.Text(),nullable=False),sa.Column('attachment_type',sa.String(30)),sa.Column('attachment_file_id',sa.String(255)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_ticket_messages_ticket_id','ticket_messages',['ticket_id'])
    op.create_table('ratings',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('ticket_id',sa.Integer(),sa.ForeignKey('tickets.id',ondelete='CASCADE'),nullable=False),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id'),nullable=False),sa.Column('score',sa.Integer(),nullable=False),sa.Column('comment',sa.Text()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_ratings_ticket_id','ratings',['ticket_id'],unique=True)
    op.create_table('feedback',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id'),nullable=False),sa.Column('text',sa.Text(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('ai_conversations',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id'),nullable=False),sa.Column('title',sa.String(255),nullable=False),sa.Column('is_closed',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_ai_conversations_user_id','ai_conversations',['user_id'])
    op.create_table('ai_messages',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('conversation_id',sa.Integer(),sa.ForeignKey('ai_conversations.id',ondelete='CASCADE'),nullable=False),sa.Column('role',sa.String(20),nullable=False),sa.Column('content',sa.Text(),nullable=False),sa.Column('model',sa.String(100)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_ai_messages_conversation_id','ai_messages',['conversation_id'])
    op.create_table('usage_daily',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id'),nullable=False),sa.Column('day',sa.String(10),nullable=False),sa.Column('ai_requests',sa.Integer(),nullable=False),sa.Column('tickets_created',sa.Integer(),nullable=False)); op.create_index('ix_usage_daily_day','usage_daily',['day']); op.create_unique_constraint('uq_usage_user_day','usage_daily',['user_id','day'])
    op.create_table('referrals',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('inviter_id',sa.Integer(),sa.ForeignKey('users.id'),nullable=False),sa.Column('invited_id',sa.Integer(),sa.ForeignKey('users.id'),nullable=False),sa.Column('source',sa.String(100),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False)); op.create_unique_constraint('uq_referral_pair','referrals',['inviter_id','invited_id'])
    op.create_table('knowledge_items',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('title',sa.String(255),nullable=False),sa.Column('content',sa.Text(),nullable=False),sa.Column('tags',postgresql.JSON(astext_type=sa.Text()),nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('learning_items',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('kind',sa.String(40),nullable=False),sa.Column('title',sa.String(255),nullable=False),sa.Column('prompt',sa.Text(),nullable=False),sa.Column('tags',postgresql.JSON(astext_type=sa.Text()),nullable=False),sa.Column('content',sa.Text()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('broadcasts',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('target_type',sa.String(30),nullable=False),sa.Column('target_value',sa.String(255)),sa.Column('message_text',sa.Text(),nullable=False),sa.Column('status',sa.String(20),nullable=False),sa.Column('sent_count',sa.Integer(),nullable=False),sa.Column('failed_count',sa.Integer(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('audit_logs',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('admin_id',sa.BigInteger(),nullable=False),sa.Column('action',sa.String(100),nullable=False),sa.Column('target_type',sa.String(50)),sa.Column('target_id',sa.String(100)),sa.Column('payload',postgresql.JSON(astext_type=sa.Text()),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_audit_logs_action','audit_logs',['action'])

def downgrade():
    for t in ['audit_logs','broadcasts','learning_items','knowledge_items','referrals','usage_daily','ai_messages','ai_conversations','feedback','ratings','ticket_messages','tickets','operators','channels','plans','users']: op.drop_table(t)
